// Companion module for Library/Dklawren/ExportPdf.md.
// Renders a Silverbullet page as a generic, readable PDF and returns the
// generated bytes; the caller is responsible for saving the document.

const HTML2PDF_URL = '/.fs/Library/Dklawren/html2pdf.bundle.min.js'

let loadPromise = null

function loadHtml2Pdf() {
  if (window.html2pdf) {
    return Promise.resolve()
  }
  if (loadPromise) {
    return loadPromise
  }
  loadPromise = new Promise((resolve, reject) => {
    const script = document.createElement('script')
    script.src = HTML2PDF_URL
    script.onload = () => {
      if (window.html2pdf) {
        resolve()
      } else {
        reject(new Error('html2pdf.js loaded but global not found'))
      }
    }
    script.onerror = () => reject(new Error('Failed to load html2pdf.js'))
    document.head.appendChild(script)
  })
  return loadPromise
}

function escapeHtml(text) {
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}

function buildPdfHtml(pageName, bodyHtml) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(pageName)}</title>
  <style>
    @page {
      size: letter;
      margin: 0.75in;
    }
    body {
      font-family: Georgia, "Times New Roman", serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      background: #fff;
      margin: 0;
      padding: 0;
    }
    h1, h2, h3, h4, h5, h6 {
      font-family: Arial, Helvetica, sans-serif;
      color: #000;
      line-height: 1.2;
      margin-top: 1.2em;
      margin-bottom: 0.6em;
    }
    h1 {
      font-size: 22pt;
      border-bottom: 1px solid #ccc;
      padding-bottom: 0.2em;
    }
    h2 { font-size: 18pt; }
    h3 { font-size: 16pt; }
    h4 { font-size: 14pt; }
    h5 { font-size: 13pt; }
    h6 { font-size: 12pt; }
    a {
      color: #000;
      text-decoration: underline;
    }
    p {
      margin: 0.6em 0;
    }
    pre, code {
      font-family: "Courier New", Courier, monospace;
      font-size: 10pt;
      background: #f5f5f5;
    }
    code {
      padding: 0.1em 0.3em;
    }
    pre {
      padding: 0.8em;
      overflow-x: auto;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    pre code {
      padding: 0;
      background: transparent;
    }
    img {
      max-width: 100%;
      height: auto;
    }
    table {
      border-collapse: collapse;
      width: 100%;
      margin: 1em 0;
    }
    th, td {
      border: 1px solid #999;
      padding: 6px;
      text-align: left;
    }
    th {
      font-weight: bold;
      background: #f5f5f5;
    }
    blockquote {
      border-left: 3px solid #999;
      margin: 1em 0;
      padding-left: 1em;
      color: #333;
    }
    ul, ol {
      margin: 0.5em 0;
      padding-left: 1.5em;
    }
    li {
      margin: 0.25em 0;
    }
    hr {
      border: none;
      border-top: 1px solid #ccc;
      margin: 1.5em 0;
    }
  </style>
</head>
<body>
  ${bodyHtml}
</body>
</html>`
}

function pageNameToPdfPath(pageName) {
  return pageName + '.pdf'
}

export async function exportPage(pageName, bodyHtml) {
  await loadHtml2Pdf()

  const fullHtml = buildPdfHtml(pageName, bodyHtml)
  const pdfPath = pageNameToPdfPath(pageName)

  const arrayBuffer = await window.html2pdf()
    .set({
      margin: [54, 54],
      filename: pdfPath,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff'
      },
      jsPDF: {
        unit: 'pt',
        format: 'letter',
        orientation: 'portrait'
      },
      pagebreak: {
        mode: ['css', 'legacy']
      }
    })
    .from(fullHtml, 'string')
    .output('arraybuffer')

  const bytes = new Uint8Array(arrayBuffer)
  return { pdfPath, bytes }
}
